version: '3.4'

services:
  weatherapidocker:
    image: ${DOCKER_REGISTRY-}weatherapidocker
    build:
      context: .
      dockerfile: WeatherApiDocker/Dockerfile
    container_name: WeatherApi-container
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
